### ISSUE TITLE
optimize hunter_config + GIT_SUBMODULE

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/drishti#456] opened 2017-05-25 05:59 UTC
As noted in #414 ...

> on change the config-id will be affected, hence every small change of package create new root directory
> (2) can be optimized with cellar system feature: #153

This is most time consuming for Android platforms, due to unpacking the SDK.

**Comment by ruslo** [comment] 2017-05-25 06:05
Duplicate of https://github.com/elucideye/drishti/issues/153

**Closed by ruslo** 2017-05-25 06:05 UTC
Labels: hunter
