### ISSUE TITLE
update travis CI configuration (LTO)

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/drishti#273] opened 2017-01-22 19:00 UTC
Travis-ci and local build scripts should be using LTO MinSizerel variants of iOS and 32-bit Android builds (at least).

The currently supported toolchain list is maintained here`${DRISHTISDK}/bin/toolchain.sh`:

```
libcxx-hid-sections-lto
ios-10-1-dep-8-0-libcxx-hid-sections-lto
android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections-lto # EDIT
```
~~~android-ndk-r10e-api-21-arm64-v8a-gcc-49-hid-sections-lto~~~

These will be exercised by `${DRISHTISDK}/bin/build-all.sh`

**Comment by ruslo** [comment] 2017-05-12 20:22
> ios-10-1-dep-8-0-libcxx-hid-sections-lto

Failed with error:

```
CMake Error at CMakeLists.txt:26 (message):
  Compiler does not support: thread_local, __thread, or declspec(thread)
```

* https://travis-ci.com/elucideye/drishti-upload/jobs/75427898

**Comment by headupinclouds** [comment] 2017-05-12 23:25
A few options:
- `ios-10-3-*`?
- C++14  (`thread_local` is part of the language standard)
- `thread-pool-cpp` alternative  (i.e., `#ifdef DRISHTI_HAS_THREAD_LOCAL` ...)

**Comment by ruslo** [comment] 2017-05-13 09:05
According to my tiny testing in Hunter the problem is about minimal deployment iOS version. With iOS 8.4 it doesn't work but it works with iOS 9.0.

So using
```
ios-nocodesign-10-1-dep-9-0-device-libcxx-hid-sections-lto
```
instead of
```
ios-nocodesign-10-1-dep-8-0-device-libcxx-hid-sections-lto
```
should do the trick.

Is it okay?

**Comment by headupinclouds** [comment] 2017-05-13 13:10
> Is it okay?

Yes.

**Comment by ruslo** [comment] 2017-05-14 08:03
Currently CI works except for GCC:
* https://travis-ci.com/elucideye/drishti/builds/45973691

I've tested GCC LTO locally with Debug (CI use Release) and got error:
```
lto1: internal compiler error: in splice_child_die, at dwarf2out.c:4706
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
lto-wrapper: /usr/bin/g++ returned 1 exit status
/usr/bin/ld: lto-wrapper failed
```

My local build works, will investigate what can be done here.

**Comment by ruslo** [comment] 2017-05-14 11:08
> My local build works, will investigate what can be done here

Using GCC 5 helps:
* https://travis-ci.com/elucideye/drishti/builds/45975369?utm_source=github_status&utm_medium=notification

Issue related to LTO discovered/fixed (doesn't affect current build but may be important in future):
* https://gitlab.kitware.com/cmake/cmake/merge_requests/838

**Comment by ruslo** [comment] 2017-05-14 11:14
Fixed by https://github.com/elucideye/drishti/pull/438

**Closed by ruslo** 2017-05-14 11:14 UTC
Labels: CI
